name: Generate Release Notes

on: 
  workflow_dispatch:
    inputs:
      new-release-tag:
        description: 'Tag name of the new release'
        required: true
        type: string
        default: 'e.g., v1.1 or v2.0'
      previous-release-reference:
        description: 'Tag name of the previous release or the commit SHA right before the first commit in the new release'
        required: true
        type: string
        default: 'e.g., v1.0 or 2f4a6b2'
      release-notes-source:
        description: 'Release Notes Source'
        required: true
        type: choice
        options:
        - Commit Messages
        - Pull Requests
        default: 'Pull Requests'
      pr-release-notes-mode:
        description: 'Release Notes Mode (only affects release notes if you chose source as pull requests)'
        required: false
        type: choice
        options:
        - Short
        - Full
        default: 'Full'

jobs:
  generate-release-notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Use The Release Notes Manager Action
        uses: Ahmed-Khaled-dev/release-notes-manager@v1
        env:
          # secrets.GITHUB_TOKEN is automatically generated by GitHub for each workflow run
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          action-type: release
          new-release-tag: ${{ inputs.new-release-tag }}
          previous-release-reference: ${{ inputs.previous-release-reference }}
          release-notes-source: ${{ inputs.release-notes-source }}
          pr-release-notes-mode: ${{ inputs.pr-release-notes-mode }}
          github-repository: ${{ github.repository }}